apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: web
              servicePort: 8910
            path: /staging
          - backend:
              serviceName: api
              servicePort: 8911
            path: /staging/api
