apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../resources


configMapGenerator:
  - name: api-env-vars
    envs:
    - api-config.env
  - name: web-env-vars
    envs:
    - web-config.env

replicas:
  - name: api
    count: 1

patchesStrategicMerge:
  - host-path.yaml
