apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../

configMapGenerator:
  - name: api-env-vars
    envs:
    - config.env
  - name: web-env-vars
    env:
    - web-config.env

replicas:
  - name: api
    count: 1
