### Force redeploy
name: "development pipeline"
on:
  push:
     branches-ignore:
        - "main"
env:
  # Build
  NODE_ENV: development
  RUNTIME_ENV: dev

  # Container Registry
  CONTAINER_REGISTRY_HOSTNAME: ghcr.io
  CONTAINER_REGISTRY_USERNAME: buildcities
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  CONTAINER_REGISTRY_REPOSITORY: buildcities
  CONTAINER_REGISTRY_IMAGE_PREFIX: buildmvp

  # Repository
  GIT_DEPLOY_REPOSITORY_NAME: buildcities/mvp-deployment
  GIT_DEPLOY_REPOSITORY_BRANCH: main
  GIT_DEPLOY_REPOSITORY_AUTHOR_NAME: buildcities
  GIT_DEPLOY_REPOSITORY_AUTHOR_EMAIL: rollymaduk@gmail.com
  GIT_DEPLOY_REPOSITORY_AUTHOR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  ### test
  test:
    uses: buildcities/composite-workflows/.github/workflows/test.yml@main
    secrets:
      token: ${{ github.token }}
  build:
    needs: test
    uses: buildcities/composite-workflows/.github/workflows/build.yml@main
    secrets:
      token: ${{ github.token }}
