### Force redeploy ###
name: 'development pipeline'
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  ### test
  test:
    env:
      NODE_OPTIONS: "--max-old-space-size=8192"
    uses: buildcities/composite-workflows/.github/workflows/test.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
