# Force redeploy
name: "development pipeline"
on:
  push:
     branches-ignore:
        - "main"
jobs:
  #
  # test
  #
  call_test_workflow:
    uses: buildcities/product_mvp/.github/workflows/test.yml
  #
  # build
  #
  call_build_workflow:
    needs:  call_test_workflow
    uses: buildcities/product_mvp/.github/workflows/build.yml

