### Force redeploy
name: 'development pipeline'
on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  ### test
  test:
    uses: buildcities/composite-workflows/.github/workflows/test.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
